Repository mui/mui-public, pull requests merged in 2023-12, with the labels that each got.

#136 [core] Rename `needTriage` to `waitingForMaintainer` and change search param
  tools-public/toolpad/pages/waitingForMaintainer/page.yml
Labels: core

#135 Upgrade Toolpad version
  tools-public/package.json
  tools-public/toolpad/pages/OverviewPage/page.yml
  tools-public/toolpad/pages/baseUiNpmKpis/page.yml
  tools-public/toolpad/pages/bundleSizes/page.yml
  tools-public/toolpad/pages/cICompletionTime/page.yml
  tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml
  tools-public/toolpad/pages/closedVsOpenedIssues/page.yml
  tools-public/toolpad/pages/communityContributors/page.yml
  tools-public/toolpad/pages/communityCore/page.yml
  tools-public/toolpad/pages/communityPRs/page.yml
  tools-public/toolpad/pages/communityPerMonth/page.yml
  tools-public/toolpad/pages/design_kits_issue_111/page.yml
  tools-public/toolpad/pages/gender/page.yml
  tools-public/toolpad/pages/genderEngineering/page.yml
  tools-public/toolpad/pages/genderManagement/page.yml
  tools-public/toolpad/pages/headCISuccessRate/page.yml
  tools-public/toolpad/pages/issueFirstComment/page.yml
  tools-public/toolpad/pages/issueWithoutProductScope/page.yml
  tools-public/toolpad/pages/joyUiNpmKpis/page.yml
  tools-public/toolpad/pages/labelActivity/page.yml
  tools-public/toolpad/pages/medianTimeToCompletion/page.yml
  tools-public/toolpad/pages/missingGitHubLabel/page.yml
  tools-public/toolpad/pages/muicomabout/page.yml
  tools-public/toolpad/pages/needtriageNotAssigned/page.yml
  tools-public/toolpad/pages/npmVersion/page.yml
  tools-public/toolpad/pages/openIssuesWithoutLabels/page.yml
  tools-public/toolpad/pages/openPRs/page.yml
  tools-public/toolpad/pages/openPrWithoutReviewer/page.yml
  tools-public/toolpad/pages/overdueRatio/page.yml
  tools-public/toolpad/pages/prWithoutLabels/page.yml
  tools-public/toolpad/pages/validateSupport/page.yml
  tools-public/toolpad/pages/zendeskFirstReply/page.yml
  tools-public/toolpad/pages/zendeskSatisfactionScore/page.yml
  tools-public/toolpad/resources/bundleSizeQueries.ts
  tools-public/toolpad/resources/functions.ts
  tools-public/toolpad/resources/queryAbout.ts
  tools-public/yarn.lock
Labels: dependencies

#134 [core] added devlake file
  tools-public/devlake/docker-compose.yml
Labels: core

#137 [core] Update `no-response` workflow
  .github/ISSUE_TEMPLATE/1.bug.yml
  .github/ISSUE_TEMPLATE/2.feature.yml
  .github/ISSUE_TEMPLATE/3.rfc.yml
  .github/workflows/ensure-triage-label.yml
  .github/workflows/mark-duplicate.yml
  .github/workflows/no-response.yml
  tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml
  tools-public/toolpad/pages/issueWithoutProductScope/page.yml
  tools-public/toolpad/pages/needtriageNotAssigned/page.yml
Labels: core

#138 [tools] Update app title
  tools-public/toolpad/pages/OverviewPage/page.yml
  tools-public/toolpad/pages/needtriageNotAssigned/page.yml
Labels: bug 🐛

#141 [tools] Correctly provide GitHub API Token
  tools-public/toolpad/pages/OverviewPage/page.yml
  tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml
  tools-public/toolpad/pages/design_kits_issue_111/page.yml
  tools-public/toolpad/pages/issueWithoutProductScope/page.yml
  tools-public/toolpad/pages/needtriageNotAssigned/page.yml
  tools-public/toolpad/pages/openIssuesWithoutLabels/page.yml
  tools-public/toolpad/pages/openPRs/page.yml
  tools-public/toolpad/pages/waitingForMaintainer/page.yml
Labels: bug 🐛
