Repository mui/mui-public, pull requests merged in 2023-08, with the labels that each got.

#125 Upgrade Toolpad
  tools-public/yarn.lock
Labels: core

#126 [tools] Upgrade dependencies to latest
  tools-public/yarn.lock
Labels: dependencies

#124 Replace charts with new chart component
  tools-public/package.json
  tools-public/toolpad/components/Chart.tsx
  tools-public/toolpad/components/NpmChart.tsx
  tools-public/toolpad/pages/baseUiNpmKpis/page.yml
  tools-public/toolpad/pages/communityCore/page.yml
  tools-public/toolpad/pages/communityPerMonth/page.yml
  tools-public/toolpad/pages/joyUiNpmKpis/page.yml
  tools-public/yarn.lock
  yarn.lock
Labels: core

#130 Re-add recharts
  tools-public/package.json
  tools-public/yarn.lock
Labels: bug 🐛

#132 [core] Add the beginning of a CI
  .circleci/config.yml
Labels: core

#133 [core] Fix CI
  .circleci/config.yml
  .eslintignore
  .eslintrc.js
  .gitignore
  contributor-dashboard-legacy/functions/test-profile-artifact.js
  contributor-dashboard-legacy/functions/test-profile-details.js
  contributor-dashboard-legacy/package.json
  contributor-dashboard-legacy/src/index.js
  contributor-dashboard-legacy/src/serviceWorker.js
  contributor-dashboard-legacy/src/setupTests.js
  package.json
  packages/eslint-plugin-material-ui/package.json
  packages/eslint-plugin-material-ui/src/index.js
  scripts/deduplicate.mjs
  tools-public/toolpad/components/Diff.tsx
  tools-public/toolpad/components/HealthBadge.tsx
  tools-public/toolpad/components/Percent.tsx
  tools-public/toolpad/components/PieChart.tsx
  tools-public/toolpad/resources/bundleSizeQueries.ts
  tools-public/toolpad/resources/functions.ts
  tools-public/toolpad/resources/queryAbout.ts
  tools-public/toolpad/resources/queryGender.ts
  tools-public/toolpad/resources/queryHeadlessLibrariesDownloads.ts
  tools-public/toolpad/resources/queryJoyUIMonthlyDownloads.ts
  tools-public/toolpad/resources/queryMUIXLabels.ts
  tools-public/toolpad/resources/queryMaterialUILabels.ts
  tools-public/toolpad/resources/queryPRs.ts
  tools-public/toolpad/resources/queryPRswithoutReviewer.ts
  tools-public/toolpad/resources/updateMuiPaidSupport.ts
  webpackBaseConfig.js
  yarn.lock
Labels: core
