Repository mui/mui-public, pull requests merged in 2024-01, with the labels that each got.

#140 [code-infra] Sync bug issue template
  .github/ISSUE_TEMPLATE/1.bug.yml
  .github/workflows/issue-cleanup.yml
Labels: enhancement, scope: code-infra

#142 [tools] Move render.com services to the starter plan
  render.yaml
Labels: core, scope: tools

#144 [core] Remove outdated Toolpad example
  render.yaml
Labels: core
