Repository mui/mui-public, pull requests merged in 2024-08, with the labels that each got.

#179 [tools] Fix broken HiBob gender metrics
  tools-public/toolpad/pages/genderEngineering/page.yml
  tools-public/toolpad/resources/queryGender.ts
Labels: bug 🐛, regression, scope: tools

#178 [infra] Create reusable workflows
  .github/workflows/reusable/add-closing-message-to-issue.yml
  .github/workflows/scripts/addClosingMessage.js
  package.json
  pnpm-lock.yaml
Labels: core, scope: infra

#182 [infra] Adjust repository slug to product id mapping
  .github/workflows/scripts/addClosingMessage.js
Labels: scope: infra

#184 [infra] Fix workflow file location
  .github/workflows/add-closing-message-to-issue.yml
Labels: bug 🐛, scope: infra

#185 [infra] Fix label removal
  .github/workflows/scripts/addClosingMessage.js
Labels: bug 🐛, scope: infra

#186 [infra] Moved first batch of workflows to the public repo
  .github/workflows/issue-cleanup.yml
  .github/workflows/issues_add-closing-message.yml
  .github/workflows/issues_body-cleanup.yml
  .github/workflows/issues_order-id-validation.yml
  .github/workflows/scripts/issues/addClosingMessage.js
  .github/workflows/scripts/issues/bodyCleanup.js
  .github/workflows/scripts/issues/orderIdValidation.js
Labels: enhancement, scope: infra

#187 [infra] Added the secret request back into the script
  .github/workflows/scripts/issues/orderIdValidation.js
Labels: bug 🐛, scope: infra

#188 [infra] Rollback to env var
  .github/workflows/issues_order-id-validation.yml
  .github/workflows/scripts/issues/orderIdValidation.js
Labels: bug 🐛, scope: infra
