Repository mui/mui-public, pull requests merged in 2024-10, with the labels that each got.

#208 [infra] Improve CSAT engagmenet message
  .github/workflows/scripts/issues/addClosingMessage.js
Labels: enhancement, scope: infra

#211 [code-infra] Improve display of bundle size diff
  tools-public/toolpad/pages/bundleSizes/page.yml
Labels: enhancement, scope: code-infra, design

#212 [code-infra] Fix deploy
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierignore
  contributor-dashboard-legacy/README.md
  contributor-dashboard-legacy/functions/circle-ci-artifacts.js
  contributor-dashboard-legacy/functions/test-profile-artifact.js
  contributor-dashboard-legacy/functions/test-profile-details.js
  contributor-dashboard-legacy/netlify.toml
  contributor-dashboard-legacy/package.json
  contributor-dashboard-legacy/pnpm-lock.yaml
  contributor-dashboard-legacy/public/index.html
  contributor-dashboard-legacy/src/App.js
  contributor-dashboard-legacy/src/components/ErrorBoundary.js
  contributor-dashboard-legacy/src/components/ForkRibbon.js
  contributor-dashboard-legacy/src/components/Heading.js
  contributor-dashboard-legacy/src/components/Webpagetests.js
  contributor-dashboard-legacy/src/index.js
  contributor-dashboard-legacy/src/pages/Landing.js
  contributor-dashboard-legacy/src/pages/SizeComparison.tsx
  contributor-dashboard-legacy/src/pages/TestProfileAnalysis.tsx
  contributor-dashboard-legacy/yarn.lock
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug 🐛, core, regression, scope: code-infra

#214 [core] Remove prettier duplication
  contributor-dashboard-legacy/functions/circle-ci-artifacts.js
  contributor-dashboard-legacy/functions/test-profile-artifact.js
  contributor-dashboard-legacy/functions/test-profile-details.js
  contributor-dashboard-legacy/package.json
  contributor-dashboard-legacy/public/index.html
  contributor-dashboard-legacy/public/manifest.json
  contributor-dashboard-legacy/src/App.js
  contributor-dashboard-legacy/src/components/ErrorBoundary.js
  contributor-dashboard-legacy/src/components/ForkRibbon.js
  contributor-dashboard-legacy/src/components/Heading.js
  contributor-dashboard-legacy/src/components/Webpagetests.js
  contributor-dashboard-legacy/src/index.css
  contributor-dashboard-legacy/src/index.js
  contributor-dashboard-legacy/src/pages/Landing.js
  contributor-dashboard-legacy/src/pages/SizeComparison.tsx
  contributor-dashboard-legacy/src/pages/TestProfileAnalysis.tsx
  contributor-dashboard-legacy/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: core

#216 Rename Toolpad repo
  .github/workflows/scripts/issues/addClosingMessage.js
Labels: core
