Repository mui/mui-public, pull requests merged in 2024-11, with the labels that each got.

#217 [infra] Action to auto-detect cherry-pick targets
  .github/workflows/prs_create-cherry-pick-pr.yml
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: enhancement, scope: infra

#231 [infra] Fix rest endpoint
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: scope: infra

#232 [infra] Fix pull request rest endpoint in workflows
  .github/workflows/scripts/prs/checkTargetBranchLabel.js
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: bug 🐛, scope: infra

#233 [infra] Fixes workflow by adding fetch depth to checkout
  .github/workflows/prs_create-cherry-pick-pr.yml
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: bug 🐛, scope: infra

#234 [infra] Improve cherry-pick workflow
  .github/workflows/prs_create-cherry-pick-pr.yml
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: enhancement, scope: infra

#235 [infra] Fix for matrix array generation
  .github/workflows/prs_create-cherry-pick-pr.yml
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: bug 🐛, scope: infra

#229 [tools-public] Update toolpad/studio to v^0.8.0
  pnpm-lock.yaml
  tools-public/package.json
  tools-public/toolpad/application.yml
  tools-public/toolpad/pages/OverviewPage/page.yml
  tools-public/toolpad/pages/baseUiNpmKpis/page.yml
  tools-public/toolpad/pages/bundleSizes/page.yml
  tools-public/toolpad/pages/cICompletionTime/page.yml
  tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml
  tools-public/toolpad/pages/closedVsOpenedIssues/page.yml
  tools-public/toolpad/pages/communityContributors/page.yml
  tools-public/toolpad/pages/communityCore/page.yml
  tools-public/toolpad/pages/communityPRs/page.yml
  tools-public/toolpad/pages/communityPerMonth/page.yml
  tools-public/toolpad/pages/design_kits_issue_111/page.yml
  tools-public/toolpad/pages/gender/page.yml
  tools-public/toolpad/pages/genderEngineering/page.yml
  tools-public/toolpad/pages/genderManagement/page.yml
  tools-public/toolpad/pages/headCISuccessRate/page.yml
  tools-public/toolpad/pages/issueFirstComment/page.yml
  tools-public/toolpad/pages/issueWithoutProductScope/page.yml
  tools-public/toolpad/pages/issuesWithoutLabels/page.yml
  tools-public/toolpad/pages/joyUiNpmKpis/page.yml
  tools-public/toolpad/pages/labelActivity/page.yml
  tools-public/toolpad/pages/medianTimeToCompletion/page.yml
  tools-public/toolpad/pages/missingGitHubLabel/page.yml
  tools-public/toolpad/pages/muicomabout/page.yml
  tools-public/toolpad/pages/needtriageNotAssigned/page.yml
  tools-public/toolpad/pages/npmVersion/page.yml
  tools-public/toolpad/pages/openPRs/page.yml
  tools-public/toolpad/pages/openPrWithoutReviewer/page.yml
  tools-public/toolpad/pages/overdueRatio/page.yml
  tools-public/toolpad/pages/prWithoutLabels/page.yml
  tools-public/toolpad/pages/validateSupport/page.yml
  tools-public/toolpad/pages/waitingForMaintainer/page.yml
  tools-public/toolpad/pages/zendeskFirstReply/page.yml
  tools-public/toolpad/pages/zendeskSatisfactionScore/page.yml
Labels: dependencies, scope: tools

#241 [infra] Request review from approving reviewers as well
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: enhancement, scope: infra

#243 [infra] Fix array operation in cherry pick workflow
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: bug 🐛, scope: infra

#244 [infra] Support other repo with cherry-pick workflow
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: scope: infra

#246 [core] Follow coding style
  .github/workflows/issues_add-closing-message.yml
  .github/workflows/issues_body-cleanup.yml
  .github/workflows/issues_order-id-validation.yml
  .github/workflows/prs_check-target-branch-label.yml
  .github/workflows/prs_create-cherry-pick-pr.yml
Labels: core

#245 [infra] Remove cherry-pick issue write permission
  .github/workflows/prs_create-cherry-pick-pr.yml
Labels: scope: infra, security

#250 [tools] Update toolpad to the latest version (v0.10.0)
  pnpm-lock.yaml
  tools-public/package.json
  tools-public/toolpad/application.yml
  tools-public/toolpad/pages/OverviewPage/page.yml
  tools-public/toolpad/pages/baseUiNpmKpis/page.yml
  tools-public/toolpad/pages/bundleSizes/page.yml
  tools-public/toolpad/pages/cICompletionTime/page.yml
  tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml
  tools-public/toolpad/pages/closedVsOpenedIssues/page.yml
  tools-public/toolpad/pages/communityContributors/page.yml
  tools-public/toolpad/pages/communityCore/page.yml
  tools-public/toolpad/pages/communityPRs/page.yml
  tools-public/toolpad/pages/communityPerMonth/page.yml
  tools-public/toolpad/pages/design_kits_issue_111/page.yml
  tools-public/toolpad/pages/gender/page.yml
  tools-public/toolpad/pages/genderEngineering/page.yml
  tools-public/toolpad/pages/genderManagement/page.yml
  tools-public/toolpad/pages/headCISuccessRate/page.yml
  tools-public/toolpad/pages/issueFirstComment/page.yml
  tools-public/toolpad/pages/issueWithoutProductScope/page.yml
  tools-public/toolpad/pages/issuesWithoutLabels/page.yml
  tools-public/toolpad/pages/joyUiNpmKpis/page.yml
  tools-public/toolpad/pages/labelActivity/page.yml
  tools-public/toolpad/pages/medianTimeToCompletion/page.yml
  tools-public/toolpad/pages/missingGitHubLabel/page.yml
  tools-public/toolpad/pages/muicomabout/page.yml
  tools-public/toolpad/pages/needtriageNotAssigned/page.yml
  tools-public/toolpad/pages/npmVersion/page.yml
  tools-public/toolpad/pages/openPRs/page.yml
  tools-public/toolpad/pages/openPrWithoutReviewer/page.yml
  tools-public/toolpad/pages/overdueRatio/page.yml
  tools-public/toolpad/pages/prWithoutLabels/page.yml
  tools-public/toolpad/pages/validateSupport/page.yml
  tools-public/toolpad/pages/waitingForMaintainer/page.yml
  tools-public/toolpad/pages/zendeskFirstReply/page.yml
  tools-public/toolpad/pages/zendeskSatisfactionScore/page.yml
Labels: scope: tools, Toolpad
