Repository mui/mui-public, pull requests merged in 2025-03, with the labels that each got.

#277 [infra] Fix workflow permission
  .github/workflows/prs_check-if-pr-has-type-label.yml
Labels: scope: infra

#279 [infra] Added 'docs' label to array
  .github/workflows/prs_check-if-pr-has-type-label.yml
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: enhancement, scope: infra

#280 [infra] Fix duplicate comments on type label check workflow
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: bug 🐛, scope: infra

#281 [core] Upgrade pnpm
  package.json
  pnpm-lock.yaml
Labels: core, dependencies, scope: code-infra

#282 [infra] Fix comment listing
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: bug 🐛, scope: infra

#283 [infra] Fix comment update params
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: bug 🐛, scope: infra

#274 [infra] Enhance closing message logic for customer feedback
  .github/workflows/scripts/issues/addClosingMessage.js
Labels: enhancement, scope: infra

#286 [infra] Fix the closing message workflow
  .github/workflows/scripts/issues/addClosingMessage.js
Labels: bug 🐛, scope: infra

#285 [infra] Fix multiple comments issue
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: bug 🐛, scope: infra

#287 [infra] Changed branch name format
  .github/workflows/prs_create-cherry-pick-pr.yml
Labels: bug 🐛, scope: infra

#288 [infra] Added workflow to handle stale issues and PRs
  .github/workflows/general_handle-stale-issues-and-prs.yml
Labels: new feature, scope: infra

#291 [infra] Fix multiple comments on type label workflow
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: bug 🐛, scope: infra

#292 [infra] Adds input to manually define operations
  .github/workflows/general_handle-stale-issues-and-prs.yml
Labels: enhancement, scope: infra

#294 [infra] Adds status labeler workflow
  .github/workflows/issues_status-label-handler.yml
  .github/workflows/scripts/issues/statusLabelHandler.js
Labels: enhancement, scope: infra

#297 [infra] Grants write permissions for actions
  .github/workflows/issues_status-label-handler.yml
Labels: bug 🐛, scope: infra

#296 [infra] Add condition to skip comment check for pull requests
  .github/workflows/issues_status-label-handler.yml
Labels: bug 🐛, scope: infra

#299 [infra] Update stale action version and add permissions section
  .github/workflows/general_handle-stale-issues-and-prs.yml
Labels: enhancement, scope: infra

#300 [infra] Refactor status label handling
  .github/workflows/scripts/issues/statusLabelHandler.js
Labels: enhancement, scope: infra
