Repository mui/mui-public, pull requests merged in 2025-02, with the labels that each got.

#268 [tools] Polish team export
  tools-public/toolpad/pages/muicomabout/page.yml
  tools-public/toolpad/resources/queryAbout.ts
Labels: enhancement, scope: tools

#270 [tools] Fix render deploy
  render.yaml
  tools-public/toolpad/pages/OverviewPage/page.yml
Labels: bug 🐛, scope: tools

#272 [code-infra] Support running GitHub Actions with cherry-pick
  .github/workflows/prs_create-cherry-pick-pr.yml
Labels: enhancement, scope: code-infra

#273 [infra] Fix secrets assignment
  .github/workflows/prs_create-cherry-pick-pr.yml
Labels: bug 🐛, scope: infra

#275 [infra] Enforce type labels on PRs
  .github/workflows/prs_check-if-pr-has-type-label.yml
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: scope: infra

#276 [infra] adds `release` to type labels
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: enhancement, scope: infra
