Repository mui/mui-public, pull requests merged in 2025-05, with the labels that each got.

#317 [core] Improve Netlify ignore logic
  apps/code-infra-dashboard/netlify.toml
Labels: core, enhancement, scope: docs-infra

#318 [core] Align with the other repositories
  package.json
Labels: core

#319 [tools] Move to new folder structure
  .eslintignore
  .eslintrc.js
  .prettierignore
  README.md
  apps/tools-public/README.md
  apps/tools-public/package.json
  apps/tools-public/toolpad/.gitignore
  apps/tools-public/toolpad/application.yml
  apps/tools-public/toolpad/components/Diff.tsx
  apps/tools-public/toolpad/components/HealthBadge.tsx
  apps/tools-public/toolpad/components/Percent.tsx
  apps/tools-public/toolpad/components/PieChart.tsx
  apps/tools-public/toolpad/pages/OverviewPage/page.yml
  apps/tools-public/toolpad/pages/baseUiNpmKpis/page.yml
  apps/tools-public/toolpad/pages/bundleSizes/page.yml
  apps/tools-public/toolpad/pages/cICompletionTime/page.yml
  apps/tools-public/toolpad/pages/closedIssuesNoNeedtriage/page.yml
  apps/tools-public/toolpad/pages/closedVsOpenedIssues/page.yml
  apps/tools-public/toolpad/pages/communityContributors/page.yml
  apps/tools-public/toolpad/pages/communityCore/page.yml
  apps/tools-public/toolpad/pages/communityPRs/page.yml
  apps/tools-public/toolpad/pages/communityPerMonth/page.yml
  apps/tools-public/toolpad/pages/design_kits_issue_111/page.yml
  apps/tools-public/toolpad/pages/gender/page.yml
  apps/tools-public/toolpad/pages/genderEngineering/page.yml
  apps/tools-public/toolpad/pages/genderManagement/page.yml
  apps/tools-public/toolpad/pages/headCISuccessRate/page.yml
  apps/tools-public/toolpad/pages/issueFirstComment/page.yml
  apps/tools-public/toolpad/pages/issueWithoutProductScope/page.yml
  apps/tools-public/toolpad/pages/issuesWithoutLabels/page.yml
  apps/tools-public/toolpad/pages/joyUiNpmKpis/page.yml
  apps/tools-public/toolpad/pages/labelActivity/page.yml
  apps/tools-public/toolpad/pages/medianTimeToCompletion/page.yml
  apps/tools-public/toolpad/pages/missingGitHubLabel/page.yml
  apps/tools-public/toolpad/pages/muicomabout/page.yml
  apps/tools-public/toolpad/pages/needtriageNotAssigned/page.yml
  apps/tools-public/toolpad/pages/npmVersion/page.yml
  apps/tools-public/toolpad/pages/openPRs/page.yml
  apps/tools-public/toolpad/pages/openPrWithoutReviewer/page.yml
  apps/tools-public/toolpad/pages/overdueRatio/page.yml
  apps/tools-public/toolpad/pages/prWithoutLabels/page.yml
  apps/tools-public/toolpad/pages/validateSupport/page.yml
  apps/tools-public/toolpad/pages/waitingForMaintainer/page.yml
  apps/tools-public/toolpad/pages/zendeskFirstReply/page.yml
  apps/tools-public/toolpad/pages/zendeskSatisfactionScore/page.yml
  apps/tools-public/toolpad/resources/bundleSizeQueries.ts
  apps/tools-public/toolpad/resources/functions.ts
  apps/tools-public/toolpad/resources/queryAbout.ts
  apps/tools-public/toolpad/resources/queryGender.ts
  apps/tools-public/toolpad/resources/queryGitHubSearchAPI.ts
  apps/tools-public/toolpad/resources/queryHeadlessLibrariesDownloads.ts
  apps/tools-public/toolpad/resources/queryJoyUIMonthlyDownloads.ts
  apps/tools-public/toolpad/resources/queryLabelsActivity.ts
  apps/tools-public/toolpad/resources/queryPRs.ts
  apps/tools-public/toolpad/resources/queryPRswithoutReviewer.ts
  apps/tools-public/toolpad/resources/updateMuiPaidSupport.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  render.yaml
Labels: enhancement, scope: tools

#324 [core] Move engine to root
  apps/code-infra-dashboard/package.json
  package.json
Labels: core, enhancement

#310 [code-infra] bring bundle size checker to mui-public
  .circleci/config.yml
  .gitignore
  CLAUDE.md
  apps/code-infra-dashboard/netlify.toml
  apps/code-infra-dashboard/package.json
  apps/code-infra-dashboard/src/App.tsx
  apps/code-infra-dashboard/src/components/GitHubPRReference.tsx
  apps/code-infra-dashboard/src/components/PRList.tsx
  apps/code-infra-dashboard/src/components/SizeChangeDisplay.tsx
  apps/code-infra-dashboard/src/hooks/useGitHubPR.ts
  apps/code-infra-dashboard/src/hooks/useGitHubPRs.ts
  apps/code-infra-dashboard/src/pages/RepositoryPRs.tsx
  apps/code-infra-dashboard/src/pages/SizeComparison.tsx
  apps/code-infra-dashboard/tsconfig.json
  package.json
  packages/bundle-size-checker/.eslintrc.cjs
  packages/bundle-size-checker/README.md
  packages/bundle-size-checker/bin/bundle-size-checker.js
  packages/bundle-size-checker/package.json
  packages/bundle-size-checker/src/browser.d.ts
  packages/bundle-size-checker/src/browser.js
  packages/bundle-size-checker/src/cli.js
  packages/bundle-size-checker/src/configLoader.js
  packages/bundle-size-checker/src/defineConfig.js
  packages/bundle-size-checker/src/fetchSnapshot.js
  packages/bundle-size-checker/src/formatUtils.js
  packages/bundle-size-checker/src/index.js
  packages/bundle-size-checker/src/renderMarkdownReport.js
  packages/bundle-size-checker/src/sizeDiff.js
  packages/bundle-size-checker/src/types.d.ts
  packages/bundle-size-checker/src/uploadSnapshot.js
  packages/bundle-size-checker/src/worker.js
  packages/bundle-size-checker/tsconfig.json
  pnpm-lock.yaml
  update-netlify-ignore.js
Labels: scope: code-infra

#327 [code-infra] Allow controlling worker concurrency
  packages/bundle-size-checker/src/cli.js
  packages/bundle-size-checker/src/types.d.ts
Labels: scope: code-infra

#328 [code-infra] Add publishing
  .github/workflows/ci.yml
  README.md
  lerna.json
  package.json
  packages/bundle-size-checker/package.json
  packages/bundle-size-checker/src/configLoader.js
  packages/bundle-size-checker/src/defineConfig.js
  packages/bundle-size-checker/src/types.d.ts
  pnpm-lock.yaml
Labels: scope: code-infra

#329 [code-infra] Add babel-plugin-display-name
  .circleci/config.yml
  package.json
  packages/babel-plugin-display-name/LICENSE
  packages/babel-plugin-display-name/README.md
  packages/babel-plugin-display-name/package.json
  packages/babel-plugin-display-name/src/index.js
  packages/babel-plugin-display-name/src/index.test.js
  packages/babel-plugin-display-name/vite.config.mts
  pnpm-lock.yaml
  vitest.config.mts
Labels: new feature, core, scope: code-infra

#333 [core] Set caching headers for mui-frontend-public
  apps/code-infra-dashboard/public/_headers
Labels: core, enhancement

#332 [code-infra] Better colors for markdown report
  .github/workflows/ci.yml
  package.json
  packages/bundle-size-checker/src/renderMarkdownReport.js
  packages/bundle-size-checker/src/types.d.ts
Labels: scope: code-infra

#335 [code-infra] Support JSX and TS in bundle scripts
  packages/bundle-size-checker/package.json
  packages/bundle-size-checker/src/cli.js
  packages/bundle-size-checker/src/configLoader.js
  packages/bundle-size-checker/src/worker.js
  pnpm-lock.yaml
Labels: scope: code-infra

#340 [code-infra] Add sanity check that replacement has actually happend
  update-netlify-ignore.js
Labels: scope: code-infra

#337 [code-infra] Vite version of bundle size monitor
  packages/bundle-size-checker/package.json
  packages/bundle-size-checker/src/cli.js
  packages/bundle-size-checker/src/types.d.ts
  packages/bundle-size-checker/src/viteBuilder.js
  packages/bundle-size-checker/src/webpackBuilder.js
  packages/bundle-size-checker/src/worker.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/bundle-size/bundle-size-checker.config.mjs
  test/bundle-size/package.json
Labels: scope: code-infra
