Repository mui/mui-public, pull requests merged in 2025-06, with the labels that each got.

#347 [infra] Remove commentHandler and change label names
  .github/workflows/scripts/prs/checkTypeLabel.js
Labels: enhancement

#345 Update renderMarkdownReport
  packages/bundle-size-checker/package.json
  packages/bundle-size-checker/src/cli.js
  packages/bundle-size-checker/src/fetchSnapshot.js
  packages/bundle-size-checker/src/index.js
  packages/bundle-size-checker/src/renderMarkdownReport.js
  packages/bundle-size-checker/src/renderMarkdownReport.test.js
  packages/bundle-size-checker/src/types.d.ts
  packages/bundle-size-checker/vite.config.mts
Labels: enhancement

#356 [infra] Update uploadSnapshot.js
  packages/bundle-size-checker/src/uploadSnapshot.js
Labels: scope: infra

#357 [infra] Add the author to the list of reviewers for a cherry-pick PR
  .github/workflows/scripts/prs/detectTargetBranch.js
Labels: enhancement, scope: support-infra

#358 [infra] Automate publishing
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  package.json
  pnpm-lock.yaml
  scripts/publish.mjs
Labels: scope: infra

#361 [infra] Fix passing auth token to pnpm
  .github/workflows/publish.yml
Labels: scope: infra

#360 [bundle-monitor] Use markdown table
  packages/bundle-size-checker/src/renderMarkdownReport.js
  packages/bundle-size-checker/src/renderMarkdownReport.test.js
Labels: scope: infra

#363 [infra] Publish only changed canary packages
  .github/workflows/publish.yml
  package.json
  pnpm-lock.yaml
  scripts/publish.mjs
  scripts/tsconfig.json
  tsconfig.json
Labels: scope: infra

#364 [infra] Set write permission in publish action
  .github/workflows/publish.yml
Labels: scope: infra

#366 feat: add npm download statistics tracking system
  .eslintignore
  .github/workflows/npm-download-stats.yml
  data/npm-versions/@base-ui-components/react.json
  data/npm-versions/@mui/material.json
  data/npm-versions/README.md
  package.json
  scripts/collect-npm-stats.ts
Labels: scope: code-infra

#368 Do not assign `displayName` to non-functions
  packages/babel-plugin-display-name/src/index.js
  packages/babel-plugin-display-name/src/index.test.js
Labels: bug 🐛, core

#370 [infra] Some fixes to auto canary publishing
  scripts/publish.mjs
Labels: scope: code-infra

#380 [infra] Sync dependencies
  apps/code-infra-dashboard/package.json
  apps/tools-public/package.json
  package.json
  packages/babel-plugin-display-name/package.json
  packages/babel-plugin-minify-errors/package.json
  packages/babel-plugin-resolve-imports/package.json
  packages/bundle-size-checker/package.json
  packages/code-infra/package.json
  packages/docs-infra/package.json
  pnpm-lock.yaml
Labels: scope: code-infra
